name: Testes E2E

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]

    container: cypress/browsers:node16.16.0-chrome107-ff107-edge

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: "http://localhost:3000"
          node-version: ${{ matrix.node-version }}
          build: npm run build
          start: npm start
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: 08c4b86a-7d32-4bbf-bf1c-d86f1278c3ab
